kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-controller
spec:
  template:
    spec:
      containers:
        - name: csi-snapshotter
          imagePullPolicy: Always
          image: gcr.io/gke-release-staging/csi-snapshotter:v2.1.1-gke.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
