kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: gcr.io/gke-release-staging/csi-provisioner:v1.0.1-gke.0
        - name: csi-attacher
          image: gcr.io/gke-release-staging/csi-attacher:v1.0.1-gke.0
        - name: gce-pd-driver
          image: gcr.io/gke-release-staging/gcp-compute-persistent-disk-csi-driver:v0.4.0-gke.0
